# Generated by Django 6.0.6 on 2026-06-23 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image_hero', models.ImageField(upload_to='blog/', verbose_name='Image principale')),
                ('extrait', models.TextField(max_length=300, verbose_name='Extrait / Résumé')),
                ('contenu', models.TextField(verbose_name='Contenu (HTML ou texte)')),
                ('auteur', models.CharField(default='Oils of Africa', max_length=150, verbose_name='Auteur')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('temps_lecture', models.PositiveIntegerField(default=5, verbose_name='Temps de lecture (min)')),
                ('en_une', models.BooleanField(default=False, verbose_name='Article à la une')),
                ('actif', models.BooleanField(default=True, verbose_name='Publié')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
            },
        ),
    ]
