# Generated by Django 6.0.6 on 2026-07-07 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], default='photo', max_length=10, verbose_name='Type')),
                ('categorie', models.CharField(blank=True, choices=[('operations', 'Opérations'), ('produits', 'Produits'), ('divers', 'Divers'), ('sourcing', 'Sourcing'), ('logistique', 'Logistique')], default='', max_length=20, verbose_name='Catégorie')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description courte (hover)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medias/photos/', verbose_name='Image')),
                ('vignette', models.ImageField(blank=True, null=True, upload_to='medias/vignettes/', verbose_name='Vignette vidéo')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL embed YouTube / Vimeo')),
                ('en_vedette', models.BooleanField(default=False, verbose_name='En vedette (vidéo principale)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['ordre'],
            },
        ),
    ]
