# Generated by Django 6.0.6 on 2026-06-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='categorie',
            field=models.CharField(blank=True, choices=[('operations', 'Opérations'), ('produits', 'Produits'), ('sourcing', 'Sourcing'), ('logistique', 'Logistique')], default='', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description courte (hover)'),
        ),
        migrations.AddField(
            model_name='media',
            name='en_vedette',
            field=models.BooleanField(default=False, verbose_name='En vedette (vidéo principale)'),
        ),
        migrations.AddField(
            model_name='media',
            name='vignette',
            field=models.ImageField(blank=True, null=True, upload_to='medias/vignettes/', verbose_name='Vignette vidéo'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medias/photos/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='media',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL embed YouTube / Vimeo'),
        ),
    ]
