# Generated by Django 6.0.6 on 2026-07-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_add_categorie_vedette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='categorie',
            field=models.CharField(blank=True, choices=[('operations', 'Opérations'), ('produits', 'Produits'), ('divers', 'Divers'), ('sourcing', 'Sourcing'), ('logistique', 'Logistique')], default='', max_length=20, verbose_name='Catégorie'),
        ),
    ]
