# Generated by Django 6.0.6 on 2026-07-07 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sujet', models.CharField(choices=[('devis', 'Demande de devis'), ('logistique', 'Logistique / Flexitanks'), ('sourcing', 'Sourcing / Partenariat'), ('autre', 'Autre')], max_length=50, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre (H1)')),
                ('description', models.TextField(verbose_name='Description (paragraphe)')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Image de fond')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(upload_to='partenaires/', verbose_name='Logo')),
                ('lien', models.URLField(blank=True, verbose_name='Site web')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('profession', models.CharField(max_length=150, verbose_name='Poste / Profession')),
                ('mail', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/', verbose_name='Photo')),
                ('role', models.CharField(choices=[('dirigeant', 'Dirigeant principal'), ('membre', 'Autre membre')], default='membre', max_length=20, verbose_name='Rôle')),
                ('departement', models.CharField(blank=True, choices=[('', '—'), ('sourcing', 'Sourcing'), ('operationnel', 'Opérationnel'), ('administratif', 'Administratif')], default='', max_length=20, verbose_name='Département')),
                ('icone', models.CharField(blank=True, default='person', max_length=60, verbose_name='Icône Material (membres)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnel',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('categorie', models.CharField(choices=[('palme', 'Palme & dérivés'), ('tropical', 'Huiles tropicales'), ('industriel', 'Industriels')], default='palme', max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image')),
                ('ffa', models.CharField(blank=True, max_length=50, verbose_name='FFA')),
                ('iv', models.CharField(blank=True, max_length=50, verbose_name="Indice d'iode (IV)")),
                ('point_fusion', models.CharField(blank=True, max_length=50, verbose_name='Point de fusion')),
                ('conditionnement', models.CharField(blank=True, max_length=100, verbose_name='Conditionnement')),
                ('origine', models.CharField(blank=True, max_length=100, verbose_name='Origine(s)')),
                ('lead_time', models.CharField(blank=True, max_length=50, verbose_name='Lead time')),
                ('usage', models.CharField(blank=True, max_length=100, verbose_name='Usage')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['ordre'],
            },
        ),
    ]
