# Generated by Django 6.0.6 on 2026-06-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('profession', models.CharField(max_length=150, verbose_name='Poste / Profession')),
                ('mail', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/', verbose_name='Photo')),
                ('role', models.CharField(choices=[('dirigeant', 'Dirigeant principal'), ('membre', 'Autre membre')], default='membre', max_length=20, verbose_name='Rôle')),
                ('icone', models.CharField(blank=True, default='person', max_length=60, verbose_name='Icône Material (membres)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnel',
                'ordering': ['ordre'],
            },
        ),
    ]
