# Generated by Django 6.0.6 on 2026-06-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_personne'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='departement',
            field=models.CharField(blank=True, choices=[('', '—'), ('sourcing', 'Sourcing'), ('operationnel', 'Opérationnel'), ('administratif', 'Administratif')], default='', max_length=20, verbose_name='Département'),
        ),
    ]
