# Generated by Django 6.0.6 on 2026-06-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('palme', 'Palme & dérivés'), ('tropical', 'Huiles tropicales'), ('industriel', 'Industriels')], default='palme', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='conditionnement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Conditionnement'),
        ),
        migrations.AddField(
            model_name='produit',
            name='ffa',
            field=models.CharField(blank=True, max_length=50, verbose_name='FFA'),
        ),
        migrations.AddField(
            model_name='produit',
            name='iv',
            field=models.CharField(blank=True, max_length=50, verbose_name="Indice d'iode (IV)"),
        ),
        migrations.AddField(
            model_name='produit',
            name='lead_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lead time'),
        ),
        migrations.AddField(
            model_name='produit',
            name='origine',
            field=models.CharField(blank=True, max_length=100, verbose_name='Origine(s)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='point_fusion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Point de fusion'),
        ),
        migrations.AddField(
            model_name='produit',
            name='usage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Usage'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image'),
        ),
    ]
